runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

# [START env_variables]
env_variables:
  TWILIO_ACCOUNT_SID: Axxxx
  TWILIO_AUTH_TOKEN: xxx
  TWILIO_NUMBER: xxx
# [END env_variables]
